# Maven Pipeline for Azure DevOps

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  LT_USERNAME: "$(USERNAME)"
  LT_ACCESS_KEY: "$(ACCESS)"
  LT_BUILD_NAME: "Kastle_WebUI_Automation_$(ENV)"

steps:
- task: JavaToolInstaller@0
  inputs:
    version: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    
- script: |
    echo "Setting JAVA_HOME..."
    export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
    export PATH=$JAVA_HOME/bin:$PATH
    export LT_BUILD_NAME="Kastle_WebUI_Automation_$(ENV)"
    printenv
    java -version
    echo $LT_USERNAME
    echo $LT_ACCESS_KEY
    echo $LT_BUILD_NAME
  displayName: 'Set JAVA_HOME and Verify Java Version'
  env:
    LT_USERNAME: $(LT_USERNAME)
    LT_ACCESS_KEY: $(LT_ACCESS_KEY)
    LT_BUILD_NAME: $(LT_BUILD_NAME)

- task: configuration@1
  inputs:
    connection: 'tunnelVarun'
    isTunnelActivate: true
    isAppAutomate: false
    isSmartUI: false

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    echo "Running mvn verify"
    echo "DEBUG: Checking LT_BUILD_NAME before Maven execution..."
    echo "LT_BUILD_NAME: '$(LT_BUILD_NAME)'"  
    mvn -version
    mvn help:system | grep LT_BUILD_NAME
    echo "Running mvn verify with LT_BUILD_NAME: $(LT_BUILD_NAME)"
    mvn clean verify -DforkCount=0 -Ddatabase=NCA-int -Denvironment=aks-int -Dwebdriver.driver=remote -DthreadCount=2 -Dcucumber.filter.tags=@KD -Dserenity.driver.capabilities="build:Kastle_WebUI_Automation_$(ENV)"
  displayName: 'Run Tests'