# Maven Pipeline for Azure DevOps

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  LT_USERNAME: 'username'
  LT_ACCESS_KEY: 'accessKey'

steps:
- task: JavaToolInstaller@0
  inputs:
    version: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'  # Fixed from `jdkSource`

- script: |
    echo "Setting JAVA_HOME..."
    export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
    export PATH=$JAVA_HOME/bin:$PATH
    java -version
  displayName: 'Set JAVA_HOME and Verify Java Version'

- task: Cache@2
  inputs:
    key: 'maven | "pom.xml"'
    path: '~/.m2/repository'
    cacheHitVar: 'CACHE_RESTORED'
  displayName: 'Cache Maven dependencies'

# Verify if `configuration@1` is a valid task
- task: configuration@1
  inputs:
    connection: 'tunnelVarun'
    isTunnelActivate: true
    isAppAutomate: false
    isSmartUI: false

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'  # Fixed from '1.11' to '17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    echo "Running mvn verify with profile 'single'"
    mvn clean verify -DforkCount=0 -Ddatabase=NCA-int -Denvironment=aks-int -Dwebdriver.driver=chrome -DthreadCount=1 -Dcucumber.filter.tags=@KD
  displayName: 'Run mvn verify with Profile: single'
