trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  LT_USERNAME: "$(USERNAME)"
  LT_ACCESS_KEY: "$(ACCESS)"
  LT_BUILD_NAME: "Kastle_WebUI_Automation_$(ENV)"

steps:
- task: JavaToolInstaller@0
  inputs:
    version: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    echo "Setting JAVA_HOME..."
    export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
    export PATH=$JAVA_HOME/bin:$PATH
    echo "Exporting LT_BUILD_NAME..."
    echo "##vso[task.setvariable variable=LT_BUILD_NAME;isOutput=true]Kastle_WebUI_Automation_$(ENV)"
    echo "LT_BUILD_NAME: $LT_BUILD_NAME"
  displayName: 'Set JAVA_HOME and Verify Java Version'

- task: configuration@1
  inputs:
    connection: 'tunnelVarun'
    isTunnelActivate: true
    isAppAutomate: false
    isSmartUI: false

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  env:
    LT_BUILD_NAME: "Kastle_WebUI_Automation_$(ENV)"

- script: |
    export LT_BUILD_NAME="Kastle_WebUI_Automation_$(ENV)"
    mvn -version
    mvn help:system | grep LT_BUILD_NAME
    echo "Executing Maven verify with LT_BUILD_NAME: $LT_BUILD_NAME"
    mvn clean verify -DforkCount=0 -Ddatabase=NCA-int -Denvironment=aks-int -Dwebdriver.driver=chrome -DthreadCount=2 -Dcucumber.filter.tags=@KD -Dwebdriver.capabilities="build:$LT_BUILD_NAME"
  displayName: 'Run Tests'
  env:
    LT_BUILD_NAME: "Kastle_WebUI_Automation_$(ENV)"
